### PR TITLE
Upgrade Makefile to be compatible with LedgerHQ/app-boilerplate

### PR DESCRIPTION
**Pull request by spalmer25**
See: https://github.com/LedgerHQ/app-boilerplate/blob/master/Makefile
Also adds a new constant `TARGET` such that:
`TARGET=nanox make` is equivalent to `BOLOS_SDK=$NANOX_SDK make`

### CODE REVIEW

**Review by ajinkyaraj-23 — COMMENTED** [review]
Can we add a way to build specific device apps without writing BOLOS_SDK thing? I mean just writing `TARGET=nanos make ` should build nanos. BOLOS_SDK is already defined in docker.  Just assign BOLOS_SDK based on TARGET.

**Comment by spalmer25** [comment]
> Can we add a way to build specific device apps without writing BOLOS_SDK thing? I mean just writing `TARGET=nanos make ` should build nanos. BOLOS_SDK is already defined in docker. Just assign BOLOS_SDK based on TARGET.

I can add something for it !

**Review by ajinkyaraj-23 — COMMENTED** [review]
Can you change the README first para with relevant docker command as i believe the ledger-app-builder is not longer in makefile. Something of this sort would be good
`docker run --rm -ti -v "$(realpath .):/app" --privileged [ghcr.io/ledgerhq/ledger-app-builder/ledger-app-dev-tools:latest](http://ghcr.io/ledgerhq/ledger-app-builder/ledger-app-dev-tools:latest) bash -c "TARGET=nanos make"`

**Review by ajinkyaraj-23 — APPROVED** [review]
LGTM.

**Pull request merged**
