### PR TITLE
Add pre commit config file

### LINKED ISSUE #8: Add pre-commit config file
- [ ] Add .pre-commit-config file
- [ ] Update clang-format to latest version

### PR DESCRIPTION
**Pull request by ajinkyaraj-23**
fixes #8 
- [x] Added pre-commit file
- [x] Updated clang-format to latest version
- [x] updated yaml formatting.

### CODE REVIEW

**Comment by emturner** [comment]
This is a really large diff, and potentially will make it harder to get the changes into the Ledger repo?

**Comment by ajinkyaraj-23** [comment]
The main change here is clang-format style. No concrete change in the code. Only formatting changes. Would it be ok If i highlight in commit message that "Only formatting changes, no code changed". Something like that? #

> This is a really large diff, and potentially will make it harder to get the changes into the Ledger repo?
> 
> If this goes to them eventually, possibly it would be worth splitting this out into a specific diff, that they can replicate, to avoid needing this change to be audited

**Comment by spalmer25** [comment]
> The main change here is clang-format style. No concrete change in the code. Only formatting changes. Would it be ok If i highlight in commit message that "Only formatting changes, no code changed". Something like that? #
> 
> > This is a really large diff, and potentially will make it harder to get the changes into the Ledger repo?
> > If this goes to them eventually, possibly it would be worth splitting this out into a specific diff, that they can replicate, to avoid needing this change to be audited

Would it be possible to have `.pre-commit-config.yaml` and still use the old version of clang (v0.11)?

**Review by spalmer25 — COMMENTED** [review]
> The main change here is clang-format style. No concrete change in the code. Only formatting changes. Would it be ok If i highlight in commit message that "Only formatting changes, no code changed". Something like that? #
> 
> > This is a really large diff, and potentially will make it harder to get the changes into the Ledger repo?
> > If this goes to them eventually, possibly it would be worth splitting this out into a specific diff, that they can replicate, to avoid needing this change to be audited

Would it be possible to have `.pre-commit-config.yaml` and still use the old version of clang (v0.11)?

**Comment by emturner** [comment]
> The main change here is clang-format style. No concrete change in the code. Only formatting changes. Would it be ok If i highlight in commit message that "Only formatting changes, no code changed". Something like that? 

I think it should be done - but in an entirely separate PR to Ledger, from the one that implements the DAL stuff if that makes sense? 

If the PR as a whole contains both formatting and impl details, it's much harder to review (yes, they can go commit by commit), but even so they would be fully within their rights to ask for a full re-audit, which we'd want to avoid

**Comment by ajinkyaraj-23** [comment]
> > The main change here is clang-format style. No concrete change in the code. Only formatting changes. Would it be ok If i highlight in commit message that "Only formatting changes, no code changed". Something like that?
> 
> I think it should be done - but in an entirely separate PR to Ledger, from the one that implements the DAL stuff if that makes sense?
> 
> If the PR as a whole contains both formatting and impl details, it's much harder to review (yes, they can go commit by commit), but even so they would be fully within their rights to ask for a full re-audit, which we'd want to avoid

Makes sense, Lets hold on to this PR until we have merged the DAL and tests in ledger repo. Its not that critical.
I will create seperate PR for documentation and makefile updates.

**Comment by ajinkyaraj-23** [comment]
Closing as this is included in #51

**Pull request closed without merging**
